### ISSUE TITLE
dilithium2

### ISSUE THREAD

**Issue by OmarKholeif** [aabmets/quantcrypt#6]
how to use something like dilithium2, cause i have found that there is only dilithium5

**Comment by aabmets** [comment]
Dilithium2 will never be supported by QuantCrypt, because I have made the conscious choice of only supporting the strongest PQ algorithms as directed by the [CNSA](https://en.wikipedia.org/wiki/Commercial_National_Security_Algorithm_Suite) advisory, which directly states [CRYSTALS-Kyber](https://en.wikipedia.org/wiki/CRYSTALS-Kyber) and [CRYSTALS-Dilithium](https://en.wikipedia.org/wiki/Lattice-based_cryptography) with **Level V parameters**. This means Dilithium5 and Kyber1024.

**Comment by OmarKholeif** [comment]
so there is no way to customize it to support dilithium2 instead of dilithium5 ? as i have an embedded system project and i think dilithium2 will be better for memory usage

**Comment by aabmets** [comment]
@OmarKholeif I don't disagree that embedded systems could benefit from more memory-optimized algorithms, but as of current date, QuantCrypt does not yet support embedded platforms which are not running on AMD or Intel desktop processors (x86). Better platform support is in my to-do list, but I just don't have the time for personal projects (read: I'm not getting paid to develop QuantCrypt). Therefore, you theoretically could work in support for Dilithium2 if you fork this repo and know how to modify the source code, but I am not going to do it.
