### ISSUE TITLE
PIP ERROR

### ISSUE THREAD

**Issue by zikzkp** [aabmets/quantcrypt#7]
pip install quantcrypt

ERROR: Could not find a version that satisfies the requirement quantcrypt (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3)
ERROR: No matching distribution found for quantcrypt

**Comment by hg0428** [comment]
Same issue here.

**Comment by hg0428** [comment]
Nevermind, reran and it worked somehow.

**Comment by aabmets** [comment]
@zikzkp QuantCrypt does not currently support any other Python version than 3.12, because doing so would require to compile the source for all Python versions separately, due to differences how CFFI interacts with Python. Maybe it's possible to compile for all Python versions separately and then include the exact binaries that match with the Python version, but that would require either creating separate PyPI packages or cramming all binaries into one package and then selecting them based on Python version. Both solutions have considerable downsides which I'm not willing to accept, so only one Python version is supported at this time. I'm open to ideas how to solve this without considerable downsides.

**Comment by zikzkp** [comment]
> @zikzkp QuantCrypt does not currently support any other Python version than 3.12, because doing so would require to compile the source for all Python versions separately, due to differences how CFFI interacts with Python. Maybe it's possible to compile for all Python versions separately and then include the exact binaries that match with the Python version, but that would require either creating separate PyPI packages or cramming all binaries into one package and then selecting them based on Python version. Both solutions have considerable downsides which I'm not willing to accept, so only one Python version is supported at this time. I'm open to ideas how to solve this without considerable downsides.

Thanks for the clarification. I probably I'm gonna use the library. How can I email you ?

**Comment by aabmets** [comment]
@zikzkp Unfortunately, I am unable to provide customer support about using this library outside of GitHub, therefore I kindly ask you to either raise a new issue or make a post in the Discussions section, which I have just enabled for this project.

**Comment by zikzkp** [comment]
> @zikzkp Unfortunately, I am unable to provide customer support outside of GitHub about using this library, therefore I kindly ask you to either raise a new issue or make a post in the Discussions section, which I have just enabled for this project.

Thanks for getting back to me. I don't believe I require support. I'd like to inquire about the license as I'm interested in using it.

**Comment by aabmets** [comment]
@zikzkp This library is licensed under the MIT license.
